### ISSUE TITLE
Align Layout NPE

### ISSUE THREAD

**Issue by RishiDesai** [wjrl/BioFabric#113]
After entering G1: SCerevisae, G2: yeast5K, Alignment: "the perfect alignment", perfect alignment: "the perfect alignment" this NPE is thrown. This isn't the case of the main alignment and perfect alignment both being the same alignment because I tested that with other files and nothing happened.

Java version = 1.8.0_51 vendor = Oracle Corporation operating system = Mac OS X
java.lang.NullPointerException
	at org.systemsbiology.biofabric.plugin.core.align.AlignCycleLayout.calcAlignPaths(AlignCycleLayout.java:626)
	at org.systemsbiology.biofabric.plugin.core.align.AlignCycleLayout.doNodeOrder(AlignCycleLayout.java:162)
	at org.systemsbiology.biofabric.plugin.core.align.AlignCycleLayout.doNodeLayout(AlignCycleLayout.java:124)
	at org.systemsbiology.biofabric.model.BioFabricNetwork.processLinks(BioFabricNetwork.java:607)
	at org.systemsbiology.biofabric.model.BioFabricNetwork.<init>(BioFabricNetwork.java:182)
	at org.systemsbiology.biofabric.io.FileLoadFlowsImpl.expensiveModelOperations(FileLoadFlowsImpl.java:2435)
	at org.systemsbiology.biofabric.io.FileLoadFlowsImpl$NewNetworkRunner.runCore(FileLoadFlowsImpl.java:2054)
	at org.systemsbiology.biofabric.worker.BackgroundWorker.runBackground(BackgroundWorker.java:96)
	at org.systemsbiology.biofabric.worker.BackgroundWorker.run(BackgroundWorker.java:81)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wjrl** [comment]
Not too worried about an exception following an exception. But I have reproduced the first one. Good catch!

**Comment by wjrl** [comment]
No longer throwing an NPE on this combination; further work on AlignCycleLayout apparently fixed it and was checked in? Closing for now unless it pops up again.
