### ISSUE TITLE
Applying NodeSimilarity Layout Produces Stack Trace

### ISSUE THREAD

**Issue by wjrl** [wjrl/BioFabric#39]
Load SimpleGOT-Conn3X.bif, apply default layout, reapply SImilarity Layout, get this:
java.lang.IllegalStateException
	at org.systemsbiology.biofabric.layouts.NodeSimilarityLayout.findBestUnseenHop(NodeSimilarityLayout.java:615)
	at org.systemsbiology.biofabric.layouts.NodeSimilarityLayout.orderByDistanceChained(NodeSimilarityLayout.java:454)
	at org.systemsbiology.biofabric.layouts.NodeSimilarityLayout.doClusteredLayoutOrder(NodeSimilarityLayout.java:197)
	at org.systemsbiology.biofabric.layouts.NodeSimilarityLayout.doClusteredLayout(NodeSimilarityLayout.java:161)

**Comment by wjrl** [comment]
Fixed casting of Integer to String for equals test
