### ISSUE TITLE
Illegal State Doing Similarity Layout

### ISSUE THREAD

**Issue by wjrl** [wjrl/BioFabric#42]
Stack dump from ISEx when doing a similarity layout on metab.bif (large network, not included):

```
java.lang.IllegalStateException
	at org.systemsbiology.biotapestry.biofabric.BioFabricNetwork.generateLinkExtents(BioFabricNetwork.java:1883)
	at org.systemsbiology.biotapestry.biofabric.BioFabricNetwork.relayoutNetwork(BioFabricNetwork.java:442)
	at org.systemsbiology.biotapestry.biofabric.BioFabricNetwork.<init>(BioFabricNetwork.java:146)
	at org.systemsbiology.biotapestry.biofabric.FabricCommands.expensiveModelOperations(FabricCommands.java:1005)
	at org.systemsbiology.biotapestry.biofabric.FabricCommands$NetworkRelayoutRunner.runCore(FabricCommands.java:4281)
	at org.systemsbiology.biotapestry.util.BackgroundWorker.runBackground(BackgroundWorker.java:85)
	at org.systemsbiology.biotapestry.util.BackgroundWorker.run(BackgroundWorker.java:70)
	at java.lang.Thread.run(Thread.java:695)      
```

Here is where the exception is thrown:
```
rels.put(nextLink.getAugRelation(), nextLink);
int[] link = new int[2];
NodeInfo srcInfo = (NodeInfo)nodeDefs_.get(source);
if (srcInfo == null) {
    System.err.println("Bad source: " + source + " from link " + nextLink + " key " + key);
    throw new IllegalStateException();
}
```

**Comment by wjrl** [comment]
Appears to have been fixed by moving to NodeIDs. Not reproducible on the tip.
