### ISSUE TITLE
Bucket Renderer (net align) Exception thrown

### ISSUE THREAD

**Issue by RishiDesai** [wjrl/BioFabric#87]
Did net align edge layout with yeast5k, yeast2k and 1.00 importance. This happened but after I closed the error dialog the network showed in the main view. But the bottom left view was all black.

Java version = 1.8.0_51 vendor = Oracle Corporation operating system = Mac OS X
java.lang.ArrayIndexOutOfBoundsException: 2
	at org.systemsbiology.biofabric.ui.render.BucketRenderer.drawLinkAnnotsForBuffer(BucketRenderer.java:509)
	at org.systemsbiology.biofabric.ui.render.BucketRenderer.drawForBuffer(BucketRenderer.java:256)
	at org.systemsbiology.biofabric.ui.render.BufferBuilder.buildHiResSlice(BufferBuilder.java:614)
	at org.systemsbiology.biofabric.ui.render.BufferBuilder.buildBuffer(BufferBuilder.java:354)
	at org.systemsbiology.biofabric.ui.render.BufferBuilder.buildBufs(BufferBuilder.java:224)
	at org.systemsbiology.biofabric.io.FileLoadFlows.expensiveModelOperations(FileLoadFlows.java:2411)
	at org.systemsbiology.biofabric.io.FileLoadFlows$NewNetworkRunner.runCore(FileLoadFlows.java:2032)
	at org.systemsbiology.biofabric.util.BackgroundWorker.runBackground(BackgroundWorker.java:85)
	at org.systemsbiology.biofabric.util.BackgroundWorker.run(BackgroundWorker.java:70)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RishiDesai** [comment]
This only happens when NetAlignEdgeLayout uses the super class's (default edge layout) link annotations method. So with NetAlignEdgeLayout's overridden link annotations method, this should never happen. I need to set default colors for NetAlignEdgeLayout's link annotations- purple, blue, red, orange, and yellow.

**Comment by RishiDesai** [comment]
I didn't realize link annots can only be grays if node annots are installed. Please disregard this entire issue.
