### ISSUE TITLE
NPE on Network recolour

### ISSUE THREAD

**Issue by RishiDesai** [wjrl/BioFabric#89]
This happens when I load a sif graph and then edit display option by changing lighten node level by .01.

Java version = 1.8.0_51 vendor = Oracle Corporation operating system = Mac OS X
java.lang.NullPointerException
	at java.awt.Dimension.setSize(Dimension.java:184)
	at org.systemsbiology.biofabric.ui.render.BucketRenderer.dimsForBuf(BucketRenderer.java:198)
	at org.systemsbiology.biofabric.ui.render.BufferBuilder.buildOneBuf(BufferBuilder.java:167)
	at org.systemsbiology.biofabric.io.FileLoadFlows.expensiveRecolorOperations(FileLoadFlows.java:2487)
	at org.systemsbiology.biofabric.io.FileLoadFlows$RecolorNetworkRunner.runCore(FileLoadFlows.java:2393)
	at org.systemsbiology.biofabric.util.BackgroundWorker.runBackground(BackgroundWorker.java:85)
	at org.systemsbiology.biofabric.util.BackgroundWorker.run(BackgroundWorker.java:70)
	at java.lang.Thread.run(Thread.java:745)

ava version = 1.8.0_51 vendor = Oracle Corporation operating system = Mac OS X
java.lang.NullPointerException
	at java.awt.Rectangle.setBounds(Rectangle.java:337)
	at org.systemsbiology.biofabric.ui.display.BioFabricOverview.installImage(BioFabricOverview.java:206)
	at org.systemsbiology.biofabric.io.FileLoadFlows.postRecolorOperations(FileLoadFlows.java:2499)
	at org.systemsbiology.biofabric.io.FileLoadFlows$NetworkRecolor.finishedRecolor(FileLoadFlows.java:2369)
	at org.systemsbiology.biofabric.io.FileLoadFlows$NetworkRecolor.cleanUpPostRepaint(FileLoadFlows.java:2364)
	at org.systemsbiology.biofabric.util.BackgroundWorkerClient.finishedWork(BackgroundWorkerClient.java:297)
	at org.systemsbiology.biofabric.util.BackgroundWorker$3.run(BackgroundWorker.java:113)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.systemsbiology.biofabric.util.BackgroundWorkerClient.launchWorker(BackgroundWorkerClient.java:119)
	at org.systemsbiology.biofabric.util.BackgroundWorkerClient.launchWorker(BackgroundWorkerClient.java:130)
	at org.systemsbiology.biofabric.io.FileLoadFlows$NetworkRecolor.doNetworkRecolor(FileLoadFlows.java:2339)
	at org.systemsbiology.biofabric.io.FileLoadFlows.doRecolor(FileLoadFlows.java:282)
	at org.systemsbiology.biofabric.cmd.CommandSet.optionsHaveChanged(CommandSet.java:350)
	at org.systemsbiology.biofabric.ui.FabricDisplayOptionsManager.setDisplayOptions(FabricDisplayOptionsManager.java:76)
	at org.systemsbiology.biofabric.cmd.CommandSet$SetDisplayOptionsAction.actionPerformed(CommandSet.java:3252)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by wjrl** [comment]
Note the workaround is to select some nodes and edges and launch a subnetwork window (rightmost toolbar window). This will prevent the NPE.

**Comment by wjrl** [comment]
Fixed
